CREATE TABLE "Main" (
	"UserId"	INTEGER NOT NULL,
	"UserName"	TEXT,
	"FirstName"	TEXT,
	"LastName"	TEXT,
	"LangCodeTelegram"	TEXT,
	"LangSelected"	TEXT,
	"IsBot"	TEXT,
	"Url"	TEXT,
	"WeekDelta"	INTEGER,
	"q1"	TEXT,
	"q2"	TEXT,
	"q3"	TEXT,
	"q4"	TEXT,
	"q5"	TEXT,
	"q6"	TEXT,
	"q7"	TEXT,
	"q8"	TEXT,
	"q9"	TEXT,
	"q10"	TEXT,
	"LastRun"	TEXT,
	PRIMARY KEY("UserId")
);